services:
  urlshort:
    image: urlshort
    hostname: urlshort
    build:
      context: .
      dockerfile: ./urlshort/Dockerfile
    restart: unless-stopped
    environment:
      GRPC_PORT: "50051"
      GRPC_GATEWAY_PORT: "8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "urls"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50051:50051"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: "urls"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_PORT: "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d urls" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
